### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by jjohnston55** [jjohnston55/DMIT-2018-Workbook#2]
Create a page that shows our suppliers and the products they offer. I will need to see info in the following "structure"

- **Supplier**:
  - Company Name
  - Contact Name
  - Phone Number
  - **Product Summary**:
    - Product Name
    - Category Name
    - Unit Price
    - Quatity/Unit
### Tasks

- [x] Create LINQ query in LinqPad
- [x] Create classes for the _Read Model_
- [x] Copy/Adapt LinqPad query to BLL method
- [x] Create page with nested repeater
